steps:
  - id: 'checkov stage'
    name: 'bridgecrew/checkov:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        checkov -d .
        # checkov -d . --use-enforcement-rules --prisma-api-url $_PCS_URL --bc-api-key $_BC_KEY --repo-id cloudbuild/yelb-gcp --quiet
    automapSubstitutions: true
  - id: 'image scan'
    name: 'gcr.io/cloud-builders/docker'
    script: |
      docker
