steps:
  - id: 'checkov stage'
    name: 'bridgecrew/checkov:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        checkov -d . --use-enforcement-rules --prisma-api-url $_PCS_URL --bc-api-key $_BC_KEY --repo-id cloudbuild/yelb-gcp --quiet
    automapSubstitutions: true
  - id: 'image scan'
    name: 'gcr.io/cloud-builders/docker'
    script: |
      docker pull nginx
      curl -k -u $_PCS_USER:$_PCS_PASS --output ./twistcli $_CONSOLE_URL/api/v1/util/twistcli
      chmod +x ./twistcli
      ./twistcli images scan --details -address $_CONSOLE_URL -u $_PCS_USER -p $_PCS_PASS nginx
